### ISSUE TITLE
Hello, how do you work with importing pmd static analysis reports?

### ISSUE THREAD

**Issue by hiagofss** [mcarvin8/apex-code-coverage-transformer#38]
Hello, I'm trying to use PMD's static analysis in conjunction with the coverage report to extract better metrics, but the sonar plugin available at https://github.com/SalesforceFoundation/salesforce-sonar-plugin is not up to date and I'm unable to compile it.

Do you also use static analysis of files? How?

**Comment by mcarvin8** [comment]
Hi. I wasn't aware of a plugin like that that imports PMD into SonarQube. Currently just using SonarQube's default rule sets in conjunction with the coverage reports created by this plugin.

**Comment by mcarvin8** [comment]
Closing since this is out of the scope of this plugin but willing to look into this more.
