### ISSUE TITLE
The file name DeployResultCheck was not found in any package directory.

### ISSUE THREAD

**Issue by jfaderanga** [mcarvin8/apex-code-coverage-transformer#8]
#### Summary
Executed the command to transform JSON api output to XML but received an error `Error (1): The file name DeployResultCheck was not found in any package directory.`

#### Steps to reproduce:
1. Execute the below command
`sf apex-code-coverage transformer transform -j ./testrun-apex/coverage/coverage.json -x ./testrun-apex/coverage/sonar-generic-coverage.xml -c ./sfdx-project.json`
2. Expects output
`The XML data has been written to /testrun-apex/coverage/sonar-generic-coverage.xml`
Actual output
`Error (1): The file name DeployResultCheck was not found in any package directory.`

**Comment by mcarvin8** [comment]
Thanks for reporting this issue @jfaderanga . Can you provide me the relative path to your DeployResultCheck file in your project and what your package directories are listed as in your `sfdx-project.json`file?

I would like to try to replicate this issue and see what's going on here with the file path check function.

**Comment by mcarvin8** [comment]
@jfaderanga - Thanks for the follow up. Makes sense to me. Let me know if you have any more concerns while using the plugin.

**Comment by mcarvin8** [comment]
@jfaderanga - So you basically want the plugin to skip over files not found in any package directory and just print that as a warning?

**Comment by mcarvin8** [comment]
@jfaderanga - Please try the latest release - `1.6.2`

This will print warnings if a file wasn't found in a package directory.

It will fail if none of the files in the JSON were found in a package directory.

See the Warnings and Errors section added to the README - https://github.com/mcarvin8/apex-code-coverage-transformer/blob/main/README.md
